### ISSUE TITLE
Get-FMCAccessPolicyRule not outputting string data for certain attributes

### ISSUE THREAD

**Issue by gregdent** [eckdd/PowerFMC#23]
String data fields include the following:

sourceZone
destZone
sourcePorts
destPorts
sourceNetworks
destNetworks

Outputs the following text for all fields: "@{objects=System.Object[]}"

**Comment by gregdent** [comment]
![image](https://user-images.githubusercontent.com/49447367/58339885-722cf100-7e42-11e9-96a5-40e7f5641229.png)

**Comment by gregdent** [comment]
Is this expected behaviour or am I executing this cmdlet incorrectly?

**Comment by eckdd** [comment]
Yes, this is expected behavior. We would not be able to convert the content of those elements into JSON and pipe them into other functions if they were not stored as objects.
